version: '2.4'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=webmaster@schulzke.space"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - frontend

  frontend:
    image: "grocy/frontend:v3.1.3-1"
    build:
      args:
        GROCY_VERSION: v3.1.3
        PLATFORM: linux/amd64
      context: .
      dockerfile: Dockerfile-grocy-frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.rule=Host(`schulzke.space`)"
      - "traefik.http.routers.grocy.entrypoints=websecure"
      - "traefik.http.routers.grocy.tls.certresolver=myresolver"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx

  backend:
    image: "grocy/backend:v3.1.3-1"
    build:
      args:
        GROCY_VERSION: v3.1.3
        PLATFORM: linux/amd64
        COMPOSER_VERSION: "2.1.5"
        COMPOSER_CHECKSUM: "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
      context: .
      dockerfile: Dockerfile-grocy-backend
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php8
      - app-db:/var/www/data
    env_file:
      - grocy.env

volumes:
  app-db:
